"""empty message

Revision ID: 276e679f244c
Revises: a48fb2e84256
Create Date: 2021-03-13 03:25:29.888191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '276e679f244c'
down_revision = 'a48fb2e84256'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stats')
    # ### end Alembic commands ###
