"""empty message

Revision ID: a48fb2e84256
Revises: 18ef633f7182
Create Date: 2021-03-13 03:13:56.877043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a48fb2e84256'
down_revision = '18ef633f7182'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hashID', sa.String(length=40), nullable=False),
    sa.Column('imageUrl', sa.String(length=512), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=10), nullable=False),
    sa.Column('notif_token', sa.String(length=64), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('interest1', sa.String(length=150), nullable=True),
    sa.Column('interest2', sa.String(length=150), nullable=True),
    sa.Column('interest3', sa.String(length=150), nullable=True),
    sa.Column('interest4', sa.String(length=150), nullable=True),
    sa.Column('interest5', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('hashID'),
    sa.UniqueConstraint('notif_token'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('block',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('blocker_hashID', sa.String(length=40), nullable=False),
    sa.Column('blockee_hashID', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['blockee_hashID'], ['user.hashID'], ),
    sa.ForeignKeyConstraint(['blocker_hashID'], ['user.hashID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friend_list',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_hashID', sa.String(length=40), nullable=False),
    sa.Column('friend_hashID', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['friend_hashID'], ['user.hashID'], ),
    sa.ForeignKeyConstraint(['user_hashID'], ['user.hashID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friend_list')
    op.drop_table('block')
    op.drop_table('user')
    # ### end Alembic commands ###
